In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [5]:
df = pd.read_csv('../data/iris.csv')
df = df.drop('Id', axis=1)

In [12]:
df.drop('Species', axis=1).apply(np.std, axis=0)

SepalLengthCm    0.825301
SepalWidthCm     0.432147
PetalLengthCm    1.758529
PetalWidthCm     0.760613
dtype: float64

In [15]:
df.groupby('Species').agg(np.std)

                 SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa           0.352490      0.381024       0.173511      0.107210
Iris-versicolor       0.516171      0.313798       0.469911      0.197753
Iris-virginica        0.635880      0.322497       0.551895      0.274650

P(L < mew < U) = 1 - significant_level(alpha)

In [23]:
def z_conf_int(sample, significant_level, sigma):
    num_samples = len(sample)
    z_score = scipy.stats.norm.ppf(1 - significant_level/2)
    X_bar = np.mean(sample)
    L = X_bar - z_score*sigma/np.sqrt(num_samples)
    U = X_bar + z_score*sigma/np.sqrt(num_samples)
    
    return L, U

In [112]:
f = lambda item: item == 'A'

In [ ]:
def f(item):
    return item == 'A'

In [114]:
f('A')

True

In [24]:
def t_conf_int(sample, significant_level):
    num_samples = len(sample)
    t_score = scipy.stats.t.ppf(1 - significant_level/2, num_samples - 1)
    X_bar = np.mean(sample)
    L = X_bar - t_score*sigma/np.sqrt(num_samples)
    U = X_bar + t_score*sigma/np.sqrt(num_samples)
    
    return L, U

In [ ]:
z_con

In [16]:
df.groupby('Species').describe().T

Species              Iris-setosa  Iris-versicolor  Iris-virginica
SepalLengthCm count    50.000000        50.000000       50.000000
              mean      5.006000         5.936000        6.588000
              std       0.352490         0.516171        0.635880
              min       4.300000         4.900000        4.900000
              25%       4.800000         5.600000        6.225000
              50%       5.000000         5.900000        6.500000
              75%       5.200000         6.300000        6.900000
              max       5.800000         7.000000        7.900000
SepalWidthCm  count    50.000000        50.000000       50.000000
              mean      3.418000         2.770000        2.974000
              std       0.381024         0.313798        0.322497
              min       2.300000         2.000000        2.200000
              25%       3.125000         2.525000        2.800000
              50%       3.400000         2.800000        3.000000
              75%       3.675000         3.000000        3.175000
              max       4.400000         3.400000        3.800000
PetalLengthCm count    50.000000        50.000000       50.000000
              mean      1.464000         4.260000        5.552000
              std       0.173511         0.469911        0.551895
              min       1.000000         3.000000        4.500000
              25%       1.400000         4.000000        5.100000
              50%       1.500000         4.350000        5.550000
              75%       1.575000         4.600000        5.875000
              max       1.900000         5.100000        6.900000
PetalWidthCm  count    50.000000        50.000000       50.000000
              mean      0.244000         1.326000        2.026000
              std       0.107210         0.197753        0.274650
              min       0.100000         1.000000        1.400000
              25%       0.200000         1.200000        1.800000
              50%       0.200000         1.300000        2.000000
              75%       0.300000         1.500000        2.300000
              max       0.600000         1.800000        2.500000